const actionTypes = {
  //USER ACTIONS
  SET_USER: 'SET_USER',
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",

  //SOCKET ACTIONS
  SET_SOCKET: 'SET_SOCKET',

  //MIDDLEWARE STATE TYPES
  PENDING: '_PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: '_REJECTED',

  //GAME ACTIONS
  SET_GAME_STATE: "SET_GAME_STATE",
}
export default actionTypes